'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ar' | 'en' | 'fr' | 'de' | 'es'

interface Translations {
  [key: string]: {
    ar: string
    en: string
    fr: string
    de: string
    es: string
  }
}

const translations: Translations = {
  home: { ar: 'الرئيسية', en: 'Home', fr: 'Accueil', de: 'Startseite', es: 'Inicio' },
  courses: { ar: 'الكورسات', en: 'Courses', fr: 'Cours', de: 'Kurse', es: 'Cursos' },
  dashboard: { ar: 'لوحة التحكم', en: 'Dashboard', fr: 'Tableau de bord', de: 'Armaturenbrett', es: 'Panel de control' },
  profile: { ar: 'الملف الشخصي', en: 'Profile', fr: 'Profil', de: 'Profil', es: 'Perfil' },
  settings: { ar: 'الإعدادات', en: 'Settings', fr: 'Paramètres', de: 'Einstellungen', es: 'Configuración' },
  logout: { ar: 'تسجيل الخروج', en: 'Logout', fr: 'Déconnexion', de: 'Abmelden', es: 'Cerrar sesión' },
  login: { ar: 'تسجيل الدخول', en: 'Login', fr: 'Connexion', de: 'Anmelden', es: 'Iniciar sesión' },
  register: { ar: 'إنشاء حساب', en: 'Register', fr: 'Inscription', de: 'Registrieren', es: 'Registrarse' },
  welcome: { ar: 'أهلاً بك', en: 'Welcome', fr: 'Bienvenue', de: 'Willkommen', es: 'Bienvenido' },
  language: { ar: 'اللغة', en: 'Language', fr: 'Langue', de: 'Sprache', es: 'Idioma' },

  welcomeBack: { ar: 'أهلاً بك مجدداً', en: 'Welcome back', fr: 'Bon retour', de: 'Willkommen zurück', es: 'Bienvenido de nuevo' },
  welcomeSubtitle: { ar: 'واصل رحلة التعلم الرقمي واكتساب المهارات البرمجية اليوم.', en: 'Continue your digital learning journey and gain programming skills today.', fr: 'Continuez votre parcours d\'apprentissage numérique et acquérez des compétences en programmation aujourd\'hui.', de: 'Setzen Sie Ihre digitale Lernreise fort und erwerben Sie heute Programmierkenntnisse.', es: 'Continúa tu viaje de aprendizaje digital y adquiere habilidades de programación hoy.' },
  continueLearning: { ar: 'متابعة التعلم الآن', en: 'Continue Learning', fr: 'Continuer l\'apprentissage', de: 'Lernen fortsetzen', es: 'Continuar aprendiendo' },
  enrolledCourses: { ar: 'الكورسات المسجلة', en: 'Enrolled Courses', fr: 'Cours inscrits', de: 'Eingeschriebene Kurse', es: 'Cursos inscritos' },
  completionRate: { ar: 'نسبة الإنجاز العام', en: 'Completion Rate', fr: 'Taux d\'achèvement', de: 'Abschlussquote', es: 'Tasa de finalización' },
  certificates: { ar: 'الشهادات المكتسبة', en: 'Certificates Earned', fr: 'Certificats obtenus', de: 'Erworbene Zertifikate', es: 'Certificados obtenidos' },
  studyHours: { ar: 'ساعات الدراسة', en: 'Study Hours', fr: 'Heures d\'étude', de: 'Studienstunden', es: 'Horas de estudio' },
  currentCourses: { ar: 'الكورسات الحالية ومستوى تقدمك', en: 'Current Courses and Your Progress', fr: 'Cours actuels et votre progrès', de: 'Aktuelle Kurse und Ihr Fortschritt', es: 'Cursos actuales y tu progreso' },
  viewCertificate: { ar: 'عرض الشهادة', en: 'View Certificate', fr: 'Voir le certificat', de: 'Zertifikat ansehen', es: 'Ver certificado' },
  certificatesIssued: { ar: 'الشهادات الصادرة لك', en: 'Certificates Issued to You', fr: 'Certificats délivrés', de: 'An Sie ausgestellte Zertifikate', es: 'Certificados emitidos' },

  searchPlaceholder: { ar: 'ابحث عن كورس...', en: 'Search for a course...', fr: 'Rechercher un cours...', de: 'Nach einem Kurs suchen...', es: 'Buscar un curso...' },
  allCategories: { ar: 'كل الأقسام', en: 'All Categories', fr: 'Toutes les catégories', de: 'Alle Kategorien', es: 'Todas las categorías' },
  courseTitle: { ar: 'Frontend Foundations - أساسيات تطوير الواجهات', en: 'Frontend Foundations - Web Development Basics', fr: 'Fondamentaux Frontend', de: 'Frontend-Grundlagen', es: 'Fundamentos de Frontend' },
  courseDescription: { ar: 'مسار برمجي متكامل يرتكز على المعايير العالمية لتطوير الواجهات والتفاعلية البرمجية.', en: 'A comprehensive programming track focused on global standards for frontend development and programming interactivity.', fr: 'Un parcours de programmation complet axé sur les normes mondiales de développement frontend.', de: 'Ein umfassender Programmierkurs, der sich auf globale Standards für die Frontend-Entwicklung konzentriert.', es: 'Un programa integral de programación centrado en estándares globales para el desarrollo frontend.' },
  instructor: { ar: 'المحاضر', en: 'Instructor', fr: 'Instructeur', de: 'Dozent', es: 'Instructor' },
  duration: { ar: 'المدة', en: 'Duration', fr: 'Durée', de: 'Dauer', es: 'Duración' },
  rating: { ar: 'التقييم', en: 'Rating', fr: 'Note', de: 'Bewertung', es: 'Calificación' },
  currentLevelLabel: { ar: 'المستوى الحالي', en: 'Current Level', fr: 'Niveau actuel', de: 'Aktuelles Level', es: 'Nivel actual' },
  resourcesInLevel: { ar: 'الموارد والدروس البرمجية في هذا المستوى', en: 'Programming Resources and Lessons in This Level', fr: 'Ressources et leçons de programmation dans ce niveau', de: 'Programmierressourcen und Lektionen in diesem Level', es: 'Recursos y lecciones de programación en este nivel' },
  openVideo: { ar: 'فتح الفيديو', en: 'Open Video', fr: 'Ouvrir la vidéo', de: 'Video öffnen', es: 'Abrir video' },
  openPDF: { ar: 'فتح PDF', en: 'Open PDF', fr: 'Ouvrir le PDF', de: 'PDF öffnen', es: 'Abrir PDF' },
  startQuiz: { ar: 'بدء الاختبار', en: 'Start Quiz', fr: 'Commencer le quiz', de: 'Quiz starten', es: 'Iniciar cuestionario' },

  instructorStudio: { ar: 'استوديو المحاضر', en: 'Instructor Studio', fr: 'Studio Instructeur', de: 'Dozentenstudio', es: 'Estudio del Instructor' },
  welcomeInstructor: { ar: 'مرحباً بك', en: 'Welcome', fr: 'Bienvenue', de: 'Willkommen', es: 'Bienvenido' },
  trackStats: { ar: 'تابع إحصائيات طلابك وأضف دورات جديدة', en: 'Track your students\' stats and add new courses', fr: 'Suivez les statistiques de vos étudiants et ajoutez de nouveaux cours', de: 'Verfolgen Sie die Statistiken Ihrer Schüler und fügen Sie neue Kurse hinzu', es: 'Sigue las estadísticas de tus estudiantes y agrega nuevos cursos' },
  certifiedInstructor: { ar: 'محاضر معتمد', en: 'Certified Instructor', fr: 'Instructeur certifié', de: 'Zertifizierter Dozent', es: 'Instructor certificado' },
  totalStudents: { ar: 'إجمالي الطلاب المسجلين', en: 'Total Enrolled Students', fr: 'Total des étudiants inscrits', de: 'Eingeschriebene Schüler insgesamt', es: 'Total de estudiantes inscritos' },
  publishedCourses: { ar: 'الدورات المنشورة', en: 'Published Courses', fr: 'Cours publiés', de: 'Veröffentlichte Kurse', es: 'Cursos publicados' },
  totalRevenue: { ar: 'الأرباح الإجمالية', en: 'Total Revenue', fr: 'Revenu total', de: 'Gesamteinnahmen', es: 'Ingresos totales' },
  avgRating: { ar: 'متوسط التقييم العام', en: 'Average Rating', fr: 'Note moyenne', de: 'Durchschnittsbewertung', es: 'Calificación promedio' },
  createNewCourse: { ar: 'إنشاء كورس برمجي جديد', en: 'Create New Programming Course', fr: 'Créer un nouveau cours de programmation', de: 'Neuen Programmierkurs erstellen', es: 'Crear nuevo curso de programación' },
  courseTitleLabel: { ar: 'عنوان الكورس البرمجي', en: 'Course Title', fr: 'Titre du cours', de: 'Kurstitel', es: 'Título del curso' },
  courseDescLabel: { ar: 'وصف الكورس والمهارات المكتسبة', en: 'Course Description and Skills Gained', fr: 'Description du cours et compétences acquises', de: 'Kursbeschreibung und erworbene Fähigkeiten', es: 'Descripción del curso y habilidades adquiridas' },
  savePublish: { ar: 'حفظ ونشر الكورس', en: 'Save and Publish', fr: 'Enregistrer et publier', de: 'Speichern und veröffentlichen', es: 'Guardar y publicar' },
  addNew: { ar: 'إضافة جديد', en: 'Add New', fr: 'Ajouter', de: 'Neu hinzufügen', es: 'Agregar nuevo' },
  addStudent: { ar: 'إضافة طالب جديد', en: 'Add New Student', fr: 'Ajouter un nouvel étudiant', de: 'Neuen Schüler hinzufügen', es: 'Agregar nuevo estudiante' },
  addInstructor: { ar: 'إضافة محاضر', en: 'Add Instructor', fr: 'Ajouter un instructeur', de: 'Dozenten hinzufügen', es: 'Agregar instructor' },
  createCourse: { ar: 'إنشاء كورس جديد', en: 'Create New Course', fr: 'Créer un nouveau cours', de: 'Neuen Kurs erstellen', es: 'Crear nuevo curso' },

  fullName: { ar: 'الاسم الكامل', en: 'Full Name', fr: 'Nom complet', de: 'Vollständiger Name', es: 'Nombre completo' },
  email: { ar: 'البريد الإلكتروني', en: 'Email', fr: 'E-mail', de: 'E-Mail', es: 'Correo electrónico' },
  password: { ar: 'كلمة المرور', en: 'Password', fr: 'Mot de passe', de: 'Passwort', es: 'Contraseña' },
  accountType: { ar: 'نوع الحساب', en: 'Account Type', fr: 'Type de compte', de: 'Kontotyp', es: 'Tipo de cuenta' },
  student: { ar: 'طالب', en: 'Student', fr: 'Étudiant', de: 'Schüler', es: 'Estudiante' },
  createAccount: { ar: 'إنشاء حساب جديد', en: 'Create New Account', fr: 'Créer un nouveau compte', de: 'Neues Konto erstellen', es: 'Crear nueva cuenta' },
  joinCommunity: { ar: 'انضم إلى مجتمع VU. COURSES التعليمي', en: 'Join the VU. COURSES Educational Community', fr: 'Rejoignez la communauté éducative VU. COURSES', de: 'Treten Sie der VU. COURSES-Bildungsgemeinschaft bei', es: 'Únete a la comunidad educativa VU. COURSES' },
  alreadyHaveAccount: { ar: 'لديك حساب بالفعل؟', en: 'Already have an account?', fr: 'Vous avez déjà un compte?', de: 'Sie haben bereits ein Konto?', es: '¿Ya tienes una cuenta?' },
  createAccountNow: { ar: 'إنشاء الحساب الآن', en: 'Create Account Now', fr: 'Créer un compte maintenant', de: 'Konto jetzt erstellen', es: 'Crear cuenta ahora' },
  loginTitle: { ar: 'تسجيل الدخول إلى المنصة', en: 'Login to Platform', fr: 'Connexion à la plateforme', de: 'Bei der Plattform anmelden', es: 'Iniciar sesión en la plataforma' },
  loginSubtitle: { ar: 'أدخل بيانات حسابك للوصول إلى لوحة التعلم الخاصة بك', en: 'Enter your account details to access your learning dashboard', fr: 'Entrez vos identifiants pour accéder à votre tableau de bord', de: 'Geben Sie Ihre Kontodaten ein, um auf Ihr Dashboard zuzugreifen', es: 'Ingresa los datos de tu cuenta para acceder a tu panel de aprendizaje' },
  enterEmail: { ar: 'example@domain.com', en: 'example@domain.com', fr: 'exemple@domaine.com', de: 'beispiel@domain.de', es: 'ejemplo@dominio.com' },
  loginButton: { ar: 'دخول للحساب', en: 'Login', fr: 'Se connecter', de: 'Anmelden', es: 'Iniciar sesión' },
  loginFailed: { ar: 'فشل تسجيل الدخول', en: 'Login failed', fr: 'Échec de la connexion', de: 'Anmeldung fehlgeschlagen', es: 'Error de inicio de sesión' },
  connectionError: { ar: 'حدث خطأ في الاتصال بالخادم', en: 'A server connection error occurred', fr: 'Une erreur de connexion au serveur est survenue', de: 'Ein Serververbindungsfehler ist aufgetreten', es: 'Ocurrió un error de conexión al servidor' },
  registerFailed: { ar: 'فشل إنشاء الحساب', en: 'Account creation failed', fr: 'Échec de la création du compte', de: 'Kontoerstellung fehlgeschlagen', es: 'Error al crear la cuenta' },
  noAccount: { ar: 'ليس لديك حساب؟', en: 'Don\'t have an account?', fr: 'Vous n\'avez pas de compte?', de: 'Sie haben kein Konto?', es: '¿No tienes una cuenta?' },
  quickLogin: { ar: 'حسابات سريعة للتجربة الفورية', en: 'Quick Login for Instant Trial', fr: 'Connexion rapide pour essai instantané', de: 'Schnellanmeldung für sofortigen Test', es: 'Inicio de sesión rápido para prueba instantánea' },
  studentLogin: { ar: 'دخول طالب', en: 'Student Login', fr: 'Connexion étudiant', de: 'Schüleranmeldung', es: 'Inicio de estudiante' },
  instructorLogin: { ar: 'دخول محاضر', en: 'Instructor Login', fr: 'Connexion instructeur', de: 'Dozentenanmeldung', es: 'Inicio de instructor' },
  adminLogin: { ar: 'دخول أدمن', en: 'Admin Login', fr: 'Connexion admin', de: 'Admin-Anmeldung', es: 'Inicio de admin' },

  createAccountTitle: { ar: 'إنشاء حساب جديد', en: 'Create New Account', fr: 'Créer un nouveau compte', de: 'Neues Konto erstellen', es: 'Crear nueva cuenta' },
  joinVUCourses: { ar: 'انضم إلى مجتمع VU. COURSES التعليمي', en: 'Join the VU. COURSES Educational Community', fr: 'Rejoignez la communauté éducative VU. COURSES', de: 'Treten Sie der VU. COURSES-Bildungsgemeinschaft bei', es: 'Únete a la comunidad educativa VU. COURSES' },
  startLearningJourney: { ar: 'ابدأ رحلتك نحو الاحتراف الآن', en: 'Start Your Journey to Professionalism Now', fr: 'Commencez votre voyage vers le professionnalisme maintenant', de: 'Starten Sie jetzt Ihre Reise zum Professionalismus', es: 'Comienza tu viaje hacia el profesionalismo ahora' },
  fullNameLabel: { ar: 'الاسم الكامل', en: 'Full Name', fr: 'Nom complet', de: 'Vollständiger Name', es: 'Nombre completo' },
  fullNamePlaceholder: { ar: 'أدخل اسمك الكريم', en: 'Enter your full name', fr: 'Entrez votre nom complet', de: 'Geben Sie Ihren vollständigen Namen ein', es: 'Ingresa tu nombre completo' },
  emailLabel: { ar: 'البريد الإلكتروني', en: 'Email', fr: 'E-mail', de: 'E-Mail', es: 'Correo electrónico' },
  emailPlaceholder: { ar: 'example@domain.com', en: 'example@domain.com', fr: 'exemple@domaine.com', de: 'beispiel@domain.de', es: 'ejemplo@dominio.com' },
  passwordLabel: { ar: 'كلمة المرور', en: 'Password', fr: 'Mot de passe', de: 'Passwort', es: 'Contraseña' },
  passwordPlaceholder: { ar: '••••••••', en: '••••••••', fr: '••••••••', de: '••••••••', es: '••••••••' },
  roleLabel: { ar: 'نوع الحساب', en: 'Account Type', fr: 'Type de compte', de: 'Kontotyp', es: 'Tipo de cuenta' },
  studentOption: { ar: 'طالب (Student)', en: 'Student', fr: 'Étudiant', de: 'Schüler', es: 'Estudiante' },
  instructorOption: { ar: 'محاضر (Instructor)', en: 'Instructor', fr: 'Instructeur', de: 'Dozent', es: 'Instructor' },
  creatingAccount: { ar: 'جاري الإنشاء...', en: 'Creating...', fr: 'Création...', de: 'Erstellen...', es: 'Creando...' },
  orDivider: { ar: 'أو', en: 'Or', fr: 'Ou', de: 'Oder', es: 'O' },
  loginLink: { ar: 'تسجيل الدخول', en: 'Login', fr: 'Se connecter', de: 'Anmelden', es: 'Iniciar sesión' },
  copyright: { ar: '© 2026 جميع الحقوق محفوظة - VU. COURSES', en: '© 2026 All Rights Reserved - VU. COURSES', fr: '© 2026 Tous droits réservés - VU. COURSES', de: '© 2026 Alle Rechte vorbehalten - VU. COURSES', es: '© 2026 Todos los derechos reservados - VU. COURSES' },

  myCourses: { ar: 'دوراتي', en: 'My Courses', fr: 'Mes cours', de: 'Meine Kurse', es: 'Mis cursos' },
  myProgress: { ar: 'تقدمي', en: 'My Progress', fr: 'Mon progrès', de: 'Mein Fortschritt', es: 'Mi progreso' },
  myCertificates: { ar: 'شهاداتي', en: 'My Certificates', fr: 'Mes certificats', de: 'Meine Zertifikate', es: 'Mis certificados' },
  favorites: { ar: 'المفضلة', en: 'Favorites', fr: 'Favoris', de: 'Favoriten', es: 'Favoritos' },
  myProfile: { ar: 'ملفي الشخصي', en: 'My Profile', fr: 'Mon profil', de: 'Mein Profil', es: 'Mi perfil' },

  notifications: { ar: 'الإشعارات والتنبيهات', en: 'Notifications and Alerts', fr: 'Notifications et alertes', de: 'Benachrichtigungen und Warnungen', es: 'Notificaciones y alertas' },
  noNotifications: { ar: 'لا توجد إشعارات جديدة حالياً', en: 'No new notifications currently', fr: 'Aucune nouvelle notification pour le moment', de: 'Derzeit keine neuen Benachrichtigungen', es: 'No hay notificaciones nuevas en este momento' },
  changeTheme: { ar: 'تغيير الثيم', en: 'Change theme', fr: 'Changer le thème', de: 'Design ändern', es: 'Cambiar tema' },

  continueLearningNow: { ar: 'متابعة التعلم الآن', en: 'Continue Learning Now', fr: 'Continuer l\'apprentissage maintenant', de: 'Jetzt weiterlernen', es: 'Continuar aprendiendo ahora' },
  continueCourse: { ar: 'متابعة الكورس', en: 'Continue Course', fr: 'Continuer le cours', de: 'Kurs fortsetzen', es: 'Continuar curso' },
  completed: { ar: 'مكتمل', en: 'Completed', fr: 'Terminé', de: 'Abgeschlossen', es: 'Completado' },
  hoursStudied: { ar: 'ساعات الدراسة', en: 'Study Hours', fr: 'Heures d\'étude', de: 'Studienstunden', es: 'Horas de estudio' },

  chat: { ar: 'المحادثات والرسائل', en: 'Chat & Messages', fr: 'Chat et messages', de: 'Chat & Nachrichten', es: 'Chat y mensajes' },
  adminMode: { ar: 'الوضع: أدمن المنصة', en: 'Mode: Platform Admin', fr: 'Mode : Administrateur', de: 'Modus: Plattformadmin', es: 'Modo: Administrador' },
  instructorMode: { ar: 'الوضع: محاضر', en: 'Mode: Instructor', fr: 'Mode : Instructeur', de: 'Modus: Dozent', es: 'Modo: Instructor' },
  studentMode: { ar: 'الوضع: طالب', en: 'Mode: Student', fr: 'Mode : Étudiant', de: 'Modus: Schüler', es: 'Modo: Estudiante' },
  roleSwitcher: { ar: 'تبديل الدور للتجربة', en: 'Switch Role for Demo', fr: 'Changer de rôle', de: 'Rolle wechseln', es: 'Cambiar rol' },
  admin: { ar: 'أدمن', en: 'Admin', fr: 'Admin', de: 'Admin', es: 'Admin' },
  userManagement: { ar: 'إدارة المستخدمين', en: 'User Management', fr: 'Gestion des utilisateurs', de: 'Benutzerverwaltung', es: 'Gestión de usuarios' },
  instructors: { ar: 'المحاضرون', en: 'Instructors', fr: 'Instructeurs', de: 'Dozenten', es: 'Instructores' },
  categories: { ar: 'الأقسام والتصنيفات', en: 'Categories', fr: 'Catégories', de: 'Kategorien', es: 'Categorías' },
  lessons: { ar: 'الدروس والوسائط', en: 'Lessons & Media', fr: 'Leçons et médias', de: 'Lektionen & Medien', es: 'Lecciones y medios' },
  payments: { ar: 'المدفوعات والمحفظة', en: 'Payments & Wallet', fr: 'Paiements et portefeuille', de: 'Zahlungen & Wallet', es: 'Pagos y billetera' },
  subscriptions: { ar: 'الاشتراكات', en: 'Subscriptions', fr: 'Abonnements', de: 'Abonnements', es: 'Suscripciones' },
  reports: { ar: 'التقارير الشاملة', en: 'Comprehensive Reports', fr: 'Rapports complets', de: 'Umfassende Berichte', es: 'Informes completos' },
  students: { ar: 'الطلاب', en: 'Students', fr: 'Étudiants', de: 'Schüler', es: 'Estudiantes' },
  assignments: { ar: 'المهام والتكليفات', en: 'Assignments', fr: 'Devoirs', de: 'Aufgaben', es: 'Tareas' },
  analytics: { ar: 'تحليلات الأداء والربح', en: 'Performance & Profit Analytics', fr: 'Analyses de performance', de: 'Leistungsanalyse', es: 'Análisis de rendimiento' },
  quizzes: { ar: 'الاختبارات', en: 'Quizzes', fr: 'Quiz', de: 'Quiz', es: 'Cuestionarios' },

  platformLabel: { ar: 'منصة التعليم البرمجي', en: 'Programming Education Platform', fr: 'Plateforme d\'éducation en programmation', de: 'Programmierbildungsplattform', es: 'Plataforma de educación en programación' },
  webDevelopment: { ar: 'تطوير البرمجيات والويب', en: 'Software and Web Development', fr: 'Développement logiciel et web', de: 'Software- und Webentwicklung', es: 'Desarrollo de software y web' },
  noLessonsYet: { ar: 'لا توجد دروس أو وسائط مضافة لهذا المستوى بعد', en: 'No lessons or media added to this level yet', fr: 'Aucune leçon ou média ajouté à ce niveau pour le moment', de: 'Noch keine Lektionen oder Medien zu diesem Level hinzugefügt', es: 'Aún no hay lecciones o medios agregados a este nivel' },
  addNewLevel: { ar: 'إضافة مستوى جديد', en: 'Add New Level', fr: 'Ajouter un nouveau niveau', de: 'Neues Level hinzufügen', es: 'Agregar nuevo nivel' },
  newLevelAdded: { ar: 'مستوى مضاف حديثاً', en: 'Newly added level', fr: 'Niveau ajouté récemment', de: 'Neu hinzugefügtes Level', es: 'Nivel agregado recientemente' },
  confirmDeleteLevel: { ar: 'هل أنت متأكد من حذف هذا المستوى؟ سيتم حذف جميع الدروس والاختبارات المرتبطة به.', en: 'Are you sure you want to delete this level? All associated lessons and quizzes will be deleted.', fr: 'Êtes-vous sûr de vouloir supprimer ce niveau ? Toutes les leçons et quiz associés seront supprimés.', de: 'Sind Sie sicher, dass Sie dieses Level löschen möchten? Alle zugehörigen Lektionen und Quiz werden gelöscht.', es: '¿Estás seguro de que quieres eliminar este nivel? Se eliminarán todas las lecciones y cuestionarios asociados.' },
  deleteLevel: { ar: 'حذف المستوى', en: 'Delete Level', fr: 'Supprimer le niveau', de: 'Level löschen', es: 'Eliminar nivel' },
  certificateTitle: { ar: 'شهادة إتمام معتمدة', en: 'Certified Completion Certificate', fr: 'Certificat d\'achèvement certifié', de: 'Zertifiziertes Abschlusszertifikat', es: 'Certificado de finalización certificado' },
  printSavePdf: { ar: 'طباعة / حفظ PDF', en: 'Print / Save PDF', fr: 'Imprimer / Enregistrer PDF', de: 'Drucken / PDF speichern', es: 'Imprimir / Guardar PDF' },
  officialCertificate: { ar: 'شهادة إتمام معتمدة', en: 'OFFICIAL CERTIFICATE OF COMPLETION', fr: 'CERTIFICAT D\'ACHÈVEMENT OFFICIEL', de: 'OFFIZIELLES ABSCHLUSSZERTIFIKAT', es: 'CERTIFICADO DE FINALIZACIÓN OFICIAL' },
  completionCertificate: { ar: 'شهادة إتمام كورس برمجي', en: 'Programming Course Completion Certificate', fr: 'Certificat d\'achèvement de cours de programmation', de: 'Programmierkurs-Abschlusszertifikat', es: 'Certificado de finalización de curso de programación' },
  certificateWitness: { ar: 'تشهد منصة VU. COURSES التعليمية بأن الطالب/ـة:', en: 'The VU. COURSES educational platform certifies that the student:', fr: 'La plateforme éducative VU. COURSES certifie que l\'étudiant :', de: 'Die VU. COURSES-Bildungsplattform bescheinigt, dass der Schüler:', es: 'La plataforma educativa VU. COURSES certifica que el estudiante:' },
  certificateSuccessText: { ar: 'قد أتم بنجاح كافة المستويات والتطبيقات البرمجية والاختبارات التقييمية لدورة:', en: 'has successfully completed all levels, programming applications, and assessment tests for the course:', fr: 'a terminé avec succès tous les niveaux, applications de programmation et tests d\'évaluation du cours :', de: 'hat alle Level, Programmieranwendungen und Bewertungstests des Kurses erfolgreich abgeschlossen:', es: 'ha completado con éxito todos los niveles, aplicaciones de programación y pruebas de evaluación del curso:' },
  issuedAt: { ar: 'تاريخ الإصدار', en: 'Issued At', fr: 'Date d\'émission', de: 'Ausgestellt am', es: 'Fecha de emisión' },
  officiallyVerified: { ar: 'موثقة رسمياً', en: 'Officially Verified', fr: 'Vérifié officiellement', de: 'Offiziell verifiziert', es: 'Verificado oficialmente' },
  quizPassed: { ar: 'تهانينا! لقد اجتزت الاختبار بنجاح', en: 'Congratulations! You passed the quiz', fr: 'Félicitations ! Vous avez réussi le quiz', de: 'Herzlichen Glückwunsch! Sie haben das Quiz bestanden', es: '¡Felicitaciones! Aprobaste el cuestionario' },
  quizFailed: { ar: 'لم تتجاوز الحد الأدنى للنجاح', en: 'You did not reach the minimum passing score', fr: 'Vous n\'avez pas atteint le score minimum requis', de: 'Sie haben die Mindestpunktzahl nicht erreicht', es: 'No alcanzaste la puntuación mínima aprobatoria' },
  yourScore: { ar: 'درجتك الحالية', en: 'Your score', fr: 'Votre score', de: 'Ihre Punktzahl', es: 'Tu puntuación' },
  requiredScore: { ar: 'النسبة المطلوبة', en: 'Required score', fr: 'Score requis', de: 'Erforderliche Punktzahl', es: 'Puntuación requerida' },
  correctAnswersDetails: { ar: 'تفاصيل الإجابات الصحيحة', en: 'Correct answers details', fr: 'Détails des réponses correctes', de: 'Details zu richtigen Antworten', es: 'Detalles de respuestas correctas' },
  correctAnswers: { ar: 'الإجابات الصحيحة', en: 'Correct answers', fr: 'Réponses correctes', de: 'Richtige Antworten', es: 'Respuestas correctas' },
  ofTotal: { ar: 'من إجمالي', en: 'of total', fr: 'sur un total de', de: 'von insgesamt', es: 'de un total de' },
  questions: { ar: 'سؤال', en: 'questions', fr: 'questions', de: 'Fragen', es: 'preguntas' },
  certificateIssued: { ar: 'تم إصدار الشهادة!', en: 'Certificate issued!', fr: 'Certificat délivré !', de: 'Zertifikat ausgestellt!', es: '¡Certificado emitido!' },
  code: { ar: 'كود', en: 'code', fr: 'code', de: 'Code', es: 'código' },
  closeQuizAndReturn: { ar: 'إغلاق الاختبار والعودة', en: 'Close quiz and return', fr: 'Fermer le quiz et revenir', de: 'Quiz schließen und zurückkehren', es: 'Cerrar cuestionario y volver' },
  noQuestionsYet: { ar: 'لا توجد أسئلة مضافة في هذا الاختبار بعد.', en: 'No questions have been added to this quiz yet.', fr: 'Aucune question n\'a encore été ajoutée à ce quiz.', de: 'Diesem Quiz wurden noch keine Fragen hinzugefügt.', es: 'Aún no se han agregado preguntas a este cuestionario.' },
  question: { ar: 'السؤال', en: 'Question', fr: 'Question', de: 'Frage', es: 'Pregunta' },
  of: { ar: 'من', en: 'of', fr: 'de', de: 'von', es: 'de' },
  requiredToPass: { ar: 'المطلوب للنجاح', en: 'Required to pass', fr: 'Requis pour réussir', de: 'Erforderlich zum Bestehen', es: 'Requerido para aprobar' },
  previous: { ar: 'السابق', en: 'Previous', fr: 'Précédent', de: 'Zurück', es: 'Anterior' },
  next: { ar: 'التالي', en: 'Next', fr: 'Suivant', de: 'Weiter', es: 'Siguiente' },
  submitting: { ar: 'جاري التسليم...', en: 'Submitting...', fr: 'Soumission...', de: 'Einreichen...', es: 'Enviando...' },
  submitQuiz: { ar: 'تسليم الاختبار', en: 'Submit quiz', fr: 'Soumettre le quiz', de: 'Quiz einreichen', es: 'Enviar cuestionario' },
  lessonCompleted: { ar: 'تم إكمال الدرس', en: 'Lesson completed', fr: 'Leçon terminée', de: 'Lektion abgeschlossen', es: 'Lección completada' },
  markAsCompleted: { ar: 'تحديد كمكتمل', en: 'Mark as completed', fr: 'Marquer comme terminé', de: 'Als abgeschlossen markieren', es: 'Marcar como completado' },
  loginRequiredTitle: { ar: 'سجّل الدخول أولاً', en: 'Please log in first', fr: 'Veuillez vous connecter d\'abord', de: 'Bitte melden Sie sich zuerst an', es: 'Inicia sesión primero' },
  loginRequiredCourse: { ar: 'للوصول إلى «{courseTitle}» ومتابعة الدروس، يلزم تسجيل الدخول أو إنشاء حساب جديد.', en: 'To access «{courseTitle}» and continue lessons, you must log in or create a new account.', fr: 'Pour accéder à «{courseTitle}» et continuer les leçons, vous devez vous connecter ou créer un nouveau compte.', de: 'Um auf «{courseTitle}» zuzugreifen und Lektionen fortzusetzen, müssen Sie sich anmelden oder ein neues Konto erstellen.', es: 'Para acceder a «{courseTitle}» y continuar las lecciones, debes iniciar sesión o crear una nueva cuenta.' },
  loginRequiredDefault: { ar: 'للوصول إلى محتوى الكورسات، يلزم تسجيل الدخول أو إنشاء حساب جديد.', en: 'To access course content, you must log in or create a new account.', fr: 'Pour accéder au contenu des cours, vous devez vous connecter ou créer un nouveau compte.', de: 'Um auf Kursinhalte zuzugreifen, müssen Sie sich anmelden oder ein neues Konto erstellen.', es: 'Para acceder al contenido del curso, debes iniciar sesión o crear una nueva cuenta.' },
  contactsAndChat: { ar: 'جهات الاتصال والدردشة', en: 'Contacts & Chat', fr: 'Contacts et chat', de: 'Kontakte & Chat', es: 'Contactos y chat' },
  startChatNow: { ar: 'ابدأ المحادثة الآن بإرسال أول رسالة.', en: 'Start the conversation now by sending your first message.', fr: 'Commencez la conversation maintenant en envoyant votre premier message.', de: 'Beginnen Sie jetzt das Gespräch, indem Sie Ihre erste Nachricht senden.', es: 'Comienza la conversación ahora enviando tu primer mensaje.' },
  typeMessagePlaceholder: { ar: 'اكتب رسالتك هنا...', en: 'Type your message here...', fr: 'Tapez votre message ici...', de: 'Geben Sie Ihre Nachricht hier ein...', es: 'Escribe tu mensaje aquí...' },
  selectContactToChat: { ar: 'اختر جهة اتصال لبدء الدردشة', en: 'Select a contact to start chatting', fr: 'Sélectionnez un contact pour commencer à discuter', de: 'Wählen Sie einen Kontakt zum Chatten', es: 'Selecciona un contacto para empezar a chatear' },
  level: { ar: 'المستوى', en: 'Level', fr: 'Niveau', de: 'Level', es: 'Nivel' },
  currentLevelLabel: { ar: 'المستوى الحالي', en: 'Current Level', fr: 'Niveau actuel', de: 'Aktuelles Level', es: 'Nivel actual' },
  resourcesInLevel: { ar: 'الموارد والدروس البرمجية في هذا المستوى', en: 'Programming Resources and Lessons in This Level', fr: 'Ressources et leçons de programmation dans ce niveau', de: 'Programmierressourcen und Lektionen in diesem Level', es: 'Recursos y lecciones de programación en este nivel' },
  videoDescription: { ar: 'مشاهدة الفيديو التعليمي والتفاعل مع التطبيق العملي مباشرة.', en: 'Watch the educational video and interact with the practical application directly.', fr: 'Regardez la vidéo éducative et interagissez avec l\'application pratique.', de: 'Sehen Sie sich das Bildungsvideo an und interagieren Sie direkt mit der praktischen Anwendung.', es: 'Ve el video educativo e interactúa con la aplicación práctica directamente.' },
  pdfDescription: { ar: 'فتح الملف النصي والمراجع البرمجية القابلة للتحميل.', en: 'Open the text file and downloadable programming references.', fr: 'Ouvrir le fichier texte et les références de programmation téléchargeables.', de: 'Öffnen Sie die Textdatei und herunterladbaren Programmierreferenzen.', es: 'Abre el archivo de texto y las referencias de programación descargables.' },
  testDescription: { ar: 'بدء الاختبار التقييمي لقياس استيعاب مفاهيم هذا المستوى.', en: 'Start the assessment test to measure understanding of this level\'s concepts.', fr: 'Commencer le test d\'évaluation pour mesurer la compréhension des concepts de ce niveau.', de: 'Starten Sie den Bewertungstest, um das Verständnis der Konzepte dieses Levels zu messen.', es: 'Inicia el test de evaluación para medir la comprensión de los conceptos de este nivel.' },
  quizQuestion1: { ar: 'ما هو الوسم الصحيح لإظهار عنوان رئيسي في HTML؟', en: 'What is the correct tag to display a main heading in HTML?', fr: 'Quelle est la balise correcte pour afficher un titre principal en HTML ?', de: 'Was ist das korrekte Tag, um eine Hauptüberschrift in HTML anzuzeigen?', es: '¿Cuál es la etiqueta correcta para mostrar un encabezado principal en HTML?' },
  quizQuestion2: { ar: 'أي الروابط التالية تستخدم لتضمين ملف CSS محلي؟', en: 'Which of the following links is used to embed a local CSS file?', fr: 'Quel lien parmi les suivants est utilisé pour intégrer un fichier CSS local ?', de: 'Welcher der folgenden Links wird verwendet, um eine lokale CSS-Datei einzubetten?', es: '¿Cuál de los siguientes enlaces se usa para incrustar un archivo CSS local?' },
  student: { ar: 'طالب', en: 'Student', fr: 'Étudiant', de: 'Schüler', es: 'Estudiante' },

  save: { ar: 'حفظ', en: 'Save', fr: 'Enregistrer', de: 'Speichern', es: 'Guardar' },
  cancel: { ar: 'إلغاء', en: 'Cancel', fr: 'Annuler', de: 'Abbrechen', es: 'Cancelar' },
  delete: { ar: 'حذف', en: 'Delete', fr: 'Supprimer', de: 'Löschen', es: 'Eliminar' },
  confirm: { ar: 'تأكيد', en: 'Confirm', fr: 'Confirmer', de: 'Bestätigen', es: 'Confirmar' },
  search: { ar: 'بحث', en: 'Search', fr: 'Rechercher', de: 'Suchen', es: 'Buscar' },
  filter: { ar: 'فلتر', en: 'Filter', fr: 'Filtrer', de: 'Filter', es: 'Filtrar' },
  add: { ar: 'إضافة', en: 'Add', fr: 'Ajouter', de: 'Hinzufügen', es: 'Agregar' },
  edit: { ar: 'تعديل', en: 'Edit', fr: 'Modifier', de: 'Bearbeiten', es: 'Editar' },
  view: { ar: 'عرض', en: 'View', fr: 'Voir', de: 'Ansehen', es: 'Ver' },
  close: { ar: 'إغلاق', en: 'Close', fr: 'Fermer', de: 'Schließen', es: 'Cerrar' },
  loading: { ar: 'جاري التحميل...', en: 'Loading...', fr: 'Chargement...', de: 'Laden...', es: 'Cargando...' },
  error: { ar: 'حدث خطأ', en: 'An error occurred', fr: 'Une erreur s\'est produite', de: 'Ein Fehler ist aufgetreten', es: 'Ocurrió un error' },
  success: { ar: 'نجاح', en: 'Success', fr: 'Succès', de: 'Erfolg', es: 'Éxito' },
  warning: { ar: 'تحذير', en: 'Warning', fr: 'Avertissement', de: 'Warnung', es: 'Advertencia' },
  confirmDelete: { ar: 'هل أنت متأكد من الحذف؟', en: 'Are you sure you want to delete?', fr: 'Êtes-vous sûr de vouloir supprimer?', de: 'Sind Sie sicher, dass Sie löschen möchten?', es: '¿Estás seguro de que quieres eliminar?' },
  noData: { ar: 'لا توجد بيانات', en: 'No data', fr: 'Aucune donnée', de: 'Keine Daten', es: 'Sin datos' },

  walletBalance: { ar: 'رصيد المحفظة', en: 'Wallet Balance', fr: 'Solde du portefeuille', de: 'Wallet-Guthaben', es: 'Saldo de la billetera' },
  currentBalance: { ar: 'الرصيد الحالي', en: 'Current Balance', fr: 'Solde actuel', de: 'Aktuelles Guthaben', es: 'Saldo actual' },
  currency: { ar: 'ج.م', en: 'EGP', fr: 'EGP', de: 'EGP', es: 'EGP' },
  chargeWallet: { ar: 'شحن المحفظة', en: 'Charge Wallet', fr: 'Recharger le portefeuille', de: 'Wallet aufladen', es: 'Cargar billetera' },
  topUpAmountPlaceholder: { ar: 'أدخل المبلغ', en: 'Enter amount', fr: 'Saisir le montant', de: 'Betrag eingeben', es: 'Ingresa el monto' },
  purchaseSuccess: { ar: 'تم الشراء بنجاح', en: 'Purchase successful', fr: 'Achat réussi', de: 'Kauf erfolgreich', es: 'Compra exitosa' },
  insufficientBalance: { ar: 'رصيد غير كافٍ', en: 'Insufficient balance', fr: 'Solde insuffisant', de: 'Guthaben nicht ausreichend', es: 'Saldo insuficiente' },
  buyCourse: { ar: 'شراء الكورس', en: 'Buy Course', fr: 'Acheter le cours', de: 'Kurs kaufen', es: 'Comprar curso' },
  coursePrice: { ar: 'سعر الكورس', en: 'Course Price', fr: 'Prix du cours', de: 'Kurspreis', es: 'Precio del curso' },

  walletBalance: { ar: 'رصيد المحفظة', en: 'Wallet Balance', fr: 'Solde du portefeuille', de: 'Wallet-Guthaben', es: 'Saldo de la billetera' },
  currentBalance: { ar: 'الرصيد الحالي', en: 'Current Balance', fr: 'Solde actuel', de: 'Aktuelles Guthaben', es: 'Saldo actual' },
  currency: { ar: 'ج.م', en: 'EGP', fr: 'EGP', de: 'EGP', es: 'EGP' },
  chargeWallet: { ar: 'شحن المحفظة', en: 'Charge Wallet', fr: 'Recharger le portefeuille', de: 'Wallet aufladen', es: 'Cargar billetera' },
  topUpAmountPlaceholder: { ar: 'أدخل المبلغ', en: 'Enter amount', fr: 'Saisir le montant', de: 'Betrag eingeben', es: 'Ingresa el monto' },
  purchaseSuccess: { ar: 'تم الشراء بنجاح', en: 'Purchase successful', fr: 'Achat réussi', de: 'Kauf erfolgreich', es: 'Compra exitosa' },
  insufficientBalance: { ar: 'رصيد غير كافٍ', en: 'Insufficient balance', fr: 'Solde insuffisant', de: 'Guthaben nicht ausreichend', es: 'Saldo insuficiente' },
  buyCourse: { ar: 'شراء الكورس', en: 'Buy Course', fr: 'Acheter le cours', de: 'Kurs kaufen', es: 'Comprar curso' },
  coursePrice: { ar: 'سعر الكورس', en: 'Course Price', fr: 'Prix du cours', de: 'Kurspreis', es: 'Precio del curso' },

  adminControlCenter: { ar: 'مركز التحكم الإداري الشامل', en: 'Admin Control Center', fr: 'Centre de contrôle administratif', de: 'Admin-Kontrollzentrum', es: 'Centro de control administrativo' },
  fullAccessAdmin: { ar: 'FULL ACCESS ADMIN', en: 'FULL ACCESS ADMIN', fr: 'FULL ACCESS ADMIN', de: 'FULL ACCESS ADMIN', es: 'FULL ACCESS ADMIN' },
  platformUsers: { ar: 'إجمالي مستخدمي المنصة', en: 'Total Platform Users', fr: 'Total des utilisateurs de la plateforme', de: 'Gesamtnutzer der Plattform', es: 'Total de usuarios de la plataforma' },
  availableCourses: { ar: 'الكورسات المتاحة', en: 'Available Courses', fr: 'Cours disponibles', de: 'Verfügbare Kurse', es: 'Cursos disponibles' },
  platformRevenue: { ar: 'إيرادات المنصة الكلية', en: 'Total Platform Revenue', fr: 'Revenu total de la plateforme', de: 'Gesamteinnahmen der Plattform', es: 'Ingresos totales de la plataforma' },
  issuedCertificates: { ar: 'الشهادات الصادرة', en: 'Issued Certificates', fr: 'Certificats délivrés', de: 'Ausgestellte Zertifikate', es: 'Certificados emitidos' },
  totalStudentsInPlatform: { ar: 'إجمالي الطلاب', en: 'Total Students', fr: 'Total des étudiants', de: 'Gesamtzahl der Schüler', es: 'Total de estudiantes' },
  totalInstructors: { ar: 'إجمالي المحاضرين', en: 'Total Instructors', fr: 'Total des instructeurs', de: 'Gesamtzahl der Dozenten', es: 'Total de instructores' },
  totalAdmins: { ar: 'إجمالي الأدمن', en: 'Total Admins', fr: 'Total des administrateurs', de: 'Gesamtzahl der Admins', es: 'Total de administradores' },
  activeUsers: { ar: 'المستخدمون النشطون', en: 'Active Users', fr: 'Utilisateurs actifs', de: 'Aktive Benutzer', es: 'Usuarios activos' },
  blockedUsers: { ar: 'المستخدمون المحظورون', en: 'Blocked Users', fr: 'Utilisateurs bloqués', de: 'Blockierte Benutzer', es: 'Usuarios bloqueados' },
  users: { ar: 'المستخدمون', en: 'Users', fr: 'Utilisateurs', de: 'Benutzer', es: 'Usuarios' },
  instructor: { ar: 'محاضر', en: 'Instructor', fr: 'Instructeur', de: 'Dozent', es: 'Instructor' },
  student: { ar: 'طالب', en: 'Student', fr: 'Étudiant', de: 'Schüler', es: 'Estudiante' },
  admin: { ar: 'أدمن', en: 'Admin', fr: 'Admin', de: 'Admin', es: 'Admin' },
  status: { ar: 'الحالة', en: 'Status', fr: 'Statut', de: 'Status', es: 'Estado' },
  active: { ar: 'نشط', en: 'Active', fr: 'Actif', de: 'Aktiv', es: 'Activo' },
  blocked: { ar: 'محظور', en: 'Blocked', fr: 'Bloqué', de: 'Blockiert', es: 'Bloqueado' },
  actions: { ar: 'الإجراءات', en: 'Actions', fr: 'Actions', de: 'Aktionen', es: 'Acciones' },
  deleteUser: { ar: 'حذف المستخدم', en: 'Delete User', fr: 'Supprimer l\'utilisateur', de: 'Benutzer löschen', es: 'Eliminar usuario' },
  editUser: { ar: 'تعديل المستخدم', en: 'Edit User', fr: 'Modifier l\'utilisateur', de: 'Benutzer bearbeiten', es: 'Editar usuario' },
  confirmDeleteUser: { ar: 'هل أنت متأكد من حذف هذا المستخدم؟', en: 'Are you sure you want to delete this user?', fr: 'Êtes-vous sûr de vouloir supprimer cet utilisateur?', de: 'Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?', es: '¿Estás seguro de que quieres eliminar este usuario?' },
  yes: { ar: 'نعم', en: 'Yes', fr: 'Oui', de: 'Ja', es: 'Sí' },
  no: { ar: 'لا', en: 'No', fr: 'Non', de: 'Nein', es: 'No' },
  createdAt: { ar: 'تاريخ الإنشاء', en: 'Created At', fr: 'Date de création', de: 'Erstellt am', es: 'Fecha de creación' },
  filterByRole: { ar: 'تصفية حسب الدور', en: 'Filter by Role', fr: 'Filtrer par rôle', de: 'Nach Rolle filtern', es: 'Filtrar por rol' },
  allRoles: { ar: 'كل الأدوار', en: 'All Roles', fr: 'Tous les rôles', de: 'Alle Rollen', es: 'Todos los roles' },
  userDeleted: { ar: 'تم حذف المستخدم بنجاح', en: 'User deleted successfully', fr: 'Utilisateur supprimé avec succès', de: 'Benutzer erfolgreich gelöscht', es: 'Usuario eliminado con éxito' },
  userUpdated: { ar: 'تم تحديث المستخدم بنجاح', en: 'User updated successfully', fr: 'Utilisateur mis à jour avec succès', de: 'Benutzer erfolgreich aktualisiert', es: 'Usuario actualizado con éxito' },
  userCreated: { ar: 'تم إنشاء المستخدم بنجاح', en: 'User created successfully', fr: 'Utilisateur créé avec succès', de: 'Benutzer erfolgreich erstellt', es: 'Usuario creado con éxito' },
  roleLabel: { ar: 'نوع الحساب', en: 'Account Type', fr: 'Type de compte', de: 'Kontotyp', es: 'Tipo de cuenta' },
  studentOption: { ar: 'طالب (Student)', en: 'Student', fr: 'Étudiant', de: 'Schüler', es: 'Estudiante' },
  instructorOption: { ar: 'محاضر (Instructor)', en: 'Instructor', fr: 'Instructeur', de: 'Dozent', es: 'Instructor' },
  adminOption: { ar: 'أدمن (Admin)', en: 'Admin', fr: 'Admin', de: 'Admin', es: 'Administrador' },
  creatingAccount: { ar: 'جاري الإنشاء...', en: 'Creating...', fr: 'Création...', de: 'Erstellen...', es: 'Creando...' },
  orDivider: { ar: 'أو', en: 'Or', fr: 'Ou', de: 'Oder', es: 'O' },
  loginLink: { ar: 'تسجيل الدخول', en: 'Login', fr: 'Se connecter', de: 'Anmelden', es: 'Iniciar sesión' },
  copyright: { ar: '© 2026 جميع الحقوق محفوظة - VU. COURSES', en: '© 2026 All Rights Reserved - VU. COURSES', fr: '© 2026 Tous droits réservés - VU. COURSES', de: '© 2026 Alle Rechte vorbehalten - VU. COURSES', es: '© 2026 Todos los derechos reservados - VU. COURSES' },
  confirmDeleteCategory: { ar: 'هل أنت متأكد من حذف هذا القسم؟', en: 'Are you sure you want to delete this category?', fr: 'Êtes-vous sûr de vouloir supprimer cette catégorie ?', de: 'Sind Sie sicher, dass Sie diese Kategorie löschen möchten?', es: '¿Estás seguro de que quieres eliminar esta categoría?' },
  manageCategories: { ar: 'إدارة الأقسام والتصنيفات', en: 'Manage Categories', fr: 'Gérer les catégories', de: 'Kategorien verwalten', es: 'Gestionar categorías' },
  categoriesDescription: { ar: 'إضافة وتعديل وحذف أقسام الكورسات', en: 'Add, edit, and delete course categories', fr: 'Ajouter, modifier et supprimer des catégories de cours', de: 'Kurskategorien hinzufügen, bearbeiten und löschen', es: 'Agregar, editar y eliminar categorías de cursos' },
  addCategory: { ar: 'إضافة قسم', en: 'Add Category', fr: 'Ajouter une catégorie', de: 'Kategorie hinzufügen', es: 'Agregar categoría' },
  editCategory: { ar: 'تعديل القسم', en: 'Edit Category', fr: 'Modifier la catégorie', de: 'Kategorie bearbeiten', es: 'Editar categoría' },
  addNewCategory: { ar: 'إضافة قسم جديد', en: 'Add New Category', fr: 'Ajouter une nouvelle catégorie', de: 'Neue Kategorie hinzufügen', es: 'Agregar nueva categoría' },
  categoryName: { ar: 'اسم القسم', en: 'Category Name', fr: 'Nom de la catégorie', de: 'Kategoriename', es: 'Nombre de la categoría' },
  descriptionOptional: { ar: 'الوصف (اختياري)', en: 'Description (optional)', fr: 'Description (optionnelle)', de: 'Beschreibung (optional)', es: 'Descripción (opcional)' },
  searchCategoriesPlaceholder: { ar: 'بحث في الأقسام...', en: 'Search in categories...', fr: 'Rechercher dans les catégories...', de: 'In Kategorien suchen...', es: 'Buscar en categorías...' },
  noCategories: { ar: 'لا يوجد أقسام', en: 'No categories', fr: 'Aucune catégorie', de: 'Keine Kategorien', es: 'Sin categorías' },
  category: { ar: 'القسم', en: 'Category', fr: 'Catégorie', de: 'Kategorie', es: 'Categoría' },
  coursesCount: { ar: 'عدد الكورسات', en: 'Courses Count', fr: 'Nombre de cours', de: 'Anzahl der Kurse', es: 'Cantidad de cursos' },
  manageInstructors: { ar: 'إدارة المحاضرين', en: 'Manage Instructors', fr: 'Gérer les instructeurs', de: 'Dozenten verwalten', es: 'Gestionar instructores' },
  instructorsDescription: { ar: 'متابعة المحاضرين وكورساتهم وأدائهم', en: 'Track instructors, their courses, and performance', fr: 'Suivre les instructeurs, leurs cours et leurs performances', de: 'Verfolgen Sie Dozenten, deren Kurse und deren Leistung', es: 'Seguir instructores, sus cursos y su rendimiento' },
  searchByNameOrEmail: { ar: 'بحث بالاسم أو البريد...', en: 'Search by name or email...', fr: 'Rechercher par nom ou e-mail...', de: 'Nach Name oder E-Mail suchen...', es: 'Buscar por nombre o correo...' },
  noInstructors: { ar: 'لا يوجد محاضرين', en: 'No instructors', fr: 'Aucun instructeur', de: 'Keine Dozenten', es: 'Sin instructores' },
  coursesTaught: { ar: 'الكورسات المعطاة', en: 'Courses Taught', fr: 'Cours enseignés', de: 'Gehaltene Kurse', es: 'Cursos impartidos' },
  noCourses: { ar: 'لا يوجد كورسات', en: 'No courses', fr: 'Aucun cours', de: 'Keine Kurse', es: 'Sin cursos' },
  suspended: { ar: 'موقوف', en: 'Suspended', fr: 'Suspendu', de: 'Ausgesetzt', es: 'Suspendido' },
  manageUsers: { ar: 'إدارة المستخدمين', en: 'Manage Users', fr: 'Gérer les utilisateurs', de: 'Benutzer verwalten', es: 'Gestionar usuarios' },
  usersDescription: { ar: 'التحكم الكامل في حسابات المستخدمين والصلاحيات', en: 'Full control over user accounts and permissions', fr: 'Contrôle total des comptes utilisateurs et des autorisations', de: 'Vollständige Kontrolle über Benutzerkonten und Berechtigungen', es: 'Control total sobre cuentas de usuario y permisos' },
  noUsers: { ar: 'لا يوجد مستخدمين', en: 'No users', fr: 'Aucun utilisateur', de: 'Keine Benutzer', es: 'Sin usuarios' },
  role: { ar: 'الدور', en: 'Role', fr: 'Rôle', de: 'Rolle', es: 'Rol' },
  amount: { ar: 'المبلغ', en: 'Amount', fr: 'Montant', de: 'Betrag', es: 'Monto' },
  editRole: { ar: 'تعديل الدور', en: 'Edit Role', fr: 'Modifier le rôle', de: 'Rolle bearbeiten', es: 'Editar rol' },
  editWallet: { ar: 'تعديل الرصيد', en: 'Edit Wallet', fr: 'Modifier le portefeuille', de: 'Wallet bearbeiten', es: 'Editar billetera' },
  confirmDeleteQuiz: { ar: 'هل أنت متأكد من حذف هذا الاختبار؟', en: 'Are you sure you want to delete this quiz?', fr: 'Êtes-vous sûr de vouloir supprimer ce quiz ?', de: 'Sind Sie sicher, dass Sie dieses Quiz löschen möchten?', es: '¿Estás seguro de que quieres eliminar este cuestionario?' },
  manageQuizzes: { ar: 'إدارة الاختبارات', en: 'Manage Quizzes', fr: 'Gérer les quiz', de: 'Quiz verwalten', es: 'Gestionar cuestionarios' },
  quizzesDescription: { ar: 'إضافة وتعديل وحذف الاختبارات', en: 'Add, edit, and delete quizzes', fr: 'Ajouter, modifier et supprimer des quiz', de: 'Quiz hinzufügen, bearbeiten und löschen', es: 'Agregar, editar y eliminar cuestionarios' },
  addQuiz: { ar: 'إضافة اختبار', en: 'Add Quiz', fr: 'Ajouter un quiz', de: 'Quiz hinzufügen', es: 'Agregar cuestionario' },
  editQuiz: { ar: 'تعديل الاختبار', en: 'Edit Quiz', fr: 'Modifier le quiz', de: 'Quiz bearbeiten', es: 'Editar cuestionario' },
  addNewQuiz: { ar: 'إضافة اختبار جديد', en: 'Add New Quiz', fr: 'Ajouter un nouveau quiz', de: 'Neues Quiz hinzufügen', es: 'Agregar nuevo cuestionario' },
  quizTitle: { ar: 'عنوان الاختبار', en: 'Quiz Title', fr: 'Titre du quiz', de: 'Quiz-Titel', es: 'Título del cuestionario' },
  passingScoreLabel: { ar: 'نقاط النجاح', en: 'Passing Score', fr: 'Score de réussite', de: 'Bestehspunktzahl', es: 'Puntuación mínima' },
  timeLabel: { ar: 'الوقت', en: 'Time', fr: 'Durée', de: 'Zeit', es: 'Tiempo' },
  minutes: { ar: 'دقيقة', en: 'minutes', fr: 'minutes', de: 'Minuten', es: 'minutos' },
  minutesShort: { ar: 'د', en: 'min', fr: 'min', de: 'min', es: 'min' },
  searchQuizzesPlaceholder: { ar: 'بحث في الاختبارات...', en: 'Search in quizzes...', fr: 'Rechercher dans les quiz...', de: 'In Quiz suchen...', es: 'Buscar en cuestionarios...' },
  noQuizzes: { ar: 'لا يوجد اختبارات', en: 'No quizzes', fr: 'Aucun quiz', de: 'Keine Quiz', es: 'Sin cuestionarios' },
  quiz: { ar: 'الاختبار', en: 'Quiz', fr: 'Quiz', de: 'Quiz', es: 'Cuestionario' },
  lesson: { ar: 'الدرس', en: 'Lesson', fr: 'Leçon', de: 'Lektion', es: 'Lección' },
  course: { ar: 'الكورس', en: 'Course', fr: 'Cours', de: 'Kurs', es: 'Curso' },
  attempts: { ar: 'المحاولات', en: 'Attempts', fr: 'Tentatives', de: 'Versuche', es: 'Intentos' },
  confirmDeletePlan: { ar: 'هل أنت متأكد من حذف هذه الخطة؟', en: 'Are you sure you want to delete this plan?', fr: 'Êtes-vous sûr de vouloir supprimer ce plan ?', de: 'Sind Sie sicher, dass Sie diesen Plan löschen möchten?', es: '¿Estás seguro de que quieres eliminar este plan?' },
  manageSubscriptions: { ar: 'إدارة الاشتراكات', en: 'Manage Subscriptions', fr: 'Gérer les abonnements', de: 'Abonnements verwalten', es: 'Gestionar suscripciones' },
  subscriptionsDescription: { ar: 'إدارة خطط الاشتراكات والاشتراكات النشطة', en: 'Manage subscription plans and active subscriptions', fr: 'Gérer les plans d\'abonnement et les abonnements actifs', de: 'Abonnementpläne und aktive Abonnements verwalten', es: 'Gestionar planes de suscripción y suscripciones activas' },
  addPlan: { ar: 'إضافة خطة', en: 'Add Plan', fr: 'Ajouter un plan', de: 'Plan hinzufügen', es: 'Agregar plan' },
  editPlan: { ar: 'تعديل الخطة', en: 'Edit Plan', fr: 'Modifier le plan', de: 'Plan bearbeiten', es: 'Editar plan' },
  addNewPlan: { ar: 'إضافة خطة جديدة', en: 'Add New Plan', fr: 'Ajouter un nouveau plan', de: 'Neuen Plan hinzufügen', es: 'Agregar nuevo plan' },
  planName: { ar: 'اسم الخطة', en: 'Plan Name', fr: 'Nom du plan', de: 'Planname', es: 'Nombre del plan' },
  price: { ar: 'السعر', en: 'Price', fr: 'Prix', de: 'Preis', es: 'Precio' },
  duration: { ar: 'المدة', en: 'Duration', fr: 'Durée', de: 'Dauer', es: 'Duración' },
  days: { ar: 'يوم', en: 'days', fr: 'jours', de: 'Tage', es: 'días' },
  features: { ar: 'الميزات', en: 'Features', fr: 'Fonctionnalités', de: 'Funktionen', es: 'Características' },
  subscriptionPlans: { ar: 'خطط الاشتراكات', en: 'Subscription Plans', fr: 'Plans d\'abonnement', de: 'Abonnementpläne', es: 'Planes de suscripción' },
  noPlans: { ar: 'لا توجد خطط', en: 'No plans', fr: 'Aucun plan', de: 'Keine Pläne', es: 'Sin planes' },
  inactive: { ar: 'متوقف', en: 'Inactive', fr: 'Inactif', de: 'Inaktiv', es: 'Inactivo' },
  activeSubscriptions: { ar: 'الاشتراكات النشطة', en: 'Active Subscriptions', fr: 'Abonnements actifs', de: 'Aktive Abonnements', es: 'Suscripciones activas' },
  noSubscriptions: { ar: 'لا يوجد اشتراكات', en: 'No subscriptions', fr: 'Aucun abonnement', de: 'Keine Abonnements', es: 'Sin suscripciones' },
  plan: { ar: 'الخطة', en: 'Plan', fr: 'Plan', de: 'Plan', es: 'Plan' },
  endDate: { ar: 'تاريخ الانتهاء', en: 'End Date', fr: 'Date de fin', de: 'Enddatum', es: 'Fecha de fin' },
  expired: { ar: 'منتهي', en: 'Expired', fr: 'Expiré', de: 'Abgelaufen', es: 'Expirado' },
  confirmDeleteLevel: { ar: 'هل أنت متأكد من حذف هذا المستوى؟', en: 'Are you sure you want to delete this level?', fr: 'Êtes-vous sûr de vouloir supprimer ce niveau ?', de: 'Sind Sie sicher, dass Sie dieses Level löschen möchten?', es: '¿Estás seguro de que quieres eliminar este nivel?' },
  manageLevels: { ar: 'إدارة المستويات', en: 'Manage Levels', fr: 'Gérer les niveaux', de: 'Level verwalten', es: 'Gestionar niveles' },
  levelsDescription: { ar: 'إضافة وتعديل وحذف مستويات الكورسات', en: 'Add, edit, and delete course levels', fr: 'Ajouter, modifier et supprimer des niveaux de cours', de: 'Kurslevel hinzufügen, bearbeiten und löschen', es: 'Agregar, editar y eliminar niveles de curso' },
  addLevel: { ar: 'إضافة مستوى', en: 'Add Level', fr: 'Ajouter un niveau', de: 'Level hinzufügen', es: 'Agregar nivel' },
  editLevel: { ar: 'تعديل المستوى', en: 'Edit Level', fr: 'Modifier le niveau', de: 'Level bearbeiten', es: 'Editar nivel' },
  addNewLevel: { ar: 'إضافة مستوى جديد', en: 'Add New Level', fr: 'Ajouter un nouveau niveau', de: 'Neues Level hinzufügen', es: 'Agregar nuevo nivel' },
  levelTitle: { ar: 'عنوان المستوى', en: 'Level Title', fr: 'Titre du niveau', de: 'Level-Titel', es: 'Título del nivel' },
  levelNumberLabel: { ar: 'رقم المستوى', en: 'Level Number', fr: 'Numéro de niveau', de: 'Level-Nummer', es: 'Número de nivel' },
  searchLevelsPlaceholder: { ar: 'بحث في المستويات...', en: 'Search in levels...', fr: 'Rechercher dans les niveaux...', de: 'In Leveln suchen...', es: 'Buscar en niveles...' },
  noLevels: { ar: 'لا يوجد مستويات', en: 'No levels', fr: 'Aucun niveau', de: 'Keine Level', es: 'Sin niveles' },
  levelNumber: { ar: 'الرقم', en: 'Number', fr: 'Numéro', de: 'Nummer', es: 'Número' },
  lessonsCount: { ar: 'عدد الدروس', en: 'Lessons Count', fr: 'Nombre de leçons', de: 'Anzahl der Lektionen', es: 'Cantidad de lecciones' },
  confirmDeleteLesson: { ar: 'هل أنت متأكد من حذف هذا الدرس؟', en: 'Are you sure you want to delete this lesson?', fr: 'Êtes-vous sûr de vouloir supprimer cette leçon ?', de: 'Sind Sie sicher, dass Sie diese Lektion löschen möchten?', es: '¿Estás seguro de que quieres eliminar esta lección?' },
  manageLessons: { ar: 'إدارة الدروس', en: 'Manage Lessons', fr: 'Gérer les leçons', de: 'Lektionen verwalten', es: 'Gestionar lecciones' },
  lessonsDescription: { ar: 'إضافة وتعديل وحذف دروس الكورسات', en: 'Add, edit, and delete course lessons', fr: 'Ajouter, modifier et supprimer des leçons de cours', de: 'Kurslektionen hinzufügen, bearbeiten und löschen', es: 'Agregar, editar y eliminar lecciones de curso' },
  addLesson: { ar: 'إضافة درس', en: 'Add Lesson', fr: 'Ajouter une leçon', de: 'Lektion hinzufügen', es: 'Agregar lección' },
  editLesson: { ar: 'تعديل الدرس', en: 'Edit Lesson', fr: 'Modifier la leçon', de: 'Lektion bearbeiten', es: 'Editar lección' },
  addNewLesson: { ar: 'إضافة درس جديد', en: 'Add New Lesson', fr: 'Ajouter une nouvelle leçon', de: 'Neue Lektion hinzufügen', es: 'Agregar nueva lección' },
  lessonTitle: { ar: 'عنوان الدرس', en: 'Lesson Title', fr: 'Titre de la leçon', de: 'Lektionstitel', es: 'Título de la lección' },
  searchLessonsPlaceholder: { ar: 'بحث في الدروس...', en: 'Search in lessons...', fr: 'Rechercher dans les leçons...', de: 'In Lektionen suchen...', es: 'Buscar en lecciones...' },
  noLessons: { ar: 'لا يوجد دروس', en: 'No lessons', fr: 'Aucune leçon', de: 'Keine Lektionen', es: 'Sin lecciones' },
  contentUrl: { ar: 'رابط المحتوى', en: 'Content URL', fr: 'URL du contenu', de: 'Inhalts-URL', es: 'URL del contenido' },
  pdfUrl: { ar: 'رابط PDF', en: 'PDF URL', fr: 'URL du PDF', de: 'PDF-URL', es: 'URL del PDF' },
  paymentsAndTransactions: { ar: 'المدفوعات والمعاملات', en: 'Payments and Transactions', fr: 'Paiements et transactions', de: 'Zahlungen und Transaktionen', es: 'Pagos y transacciones' },
  paymentsDescription: { ar: 'متابعة جميع المدفوعات والتحويلات المالية', en: 'Track all payments and financial transfers', fr: 'Suivre tous les paiements et transferts financiers', de: 'Verfolgen Sie alle Zahlungen und Finanztransfers', es: 'Seguir todos los pagos y transferencias financieras' },
  transactions: { ar: 'معاملة', en: 'transactions', fr: 'transactions', de: 'Transaktionen', es: 'transacciones' },
  allStatuses: { ar: 'كل الحالات', en: 'All statuses', fr: 'Tous les statuts', de: 'Alle Status', es: 'Todos los estados' },
  pending: { ar: 'معلقة', en: 'Pending', fr: 'En attente', de: 'Ausstehend', es: 'Pendiente' },
  failed: { ar: 'فاشلة', en: 'Failed', fr: 'Échoué', de: 'Fehlgeschlagen', es: 'Fallido' },
  refunded: { ar: 'مرجعة', en: 'Refunded', fr: 'Remboursé', de: 'Erstattet', es: 'Reembolsado' },
  from: { ar: 'من', en: 'From', fr: 'De', de: 'Von', es: 'Desde' },
  to: { ar: 'إلى', en: 'To', fr: 'À', de: 'Bis', es: 'Hasta' },
  apply: { ar: 'تطبيق', en: 'Apply', fr: 'Appliquer', de: 'Anwenden', es: 'Aplicar' },
  noTransactions: { ar: 'لا يوجد معاملات', en: 'No transactions', fr: 'Aucune transaction', de: 'Keine Transaktionen', es: 'Sin transacciones' },
  paymentMethod: { ar: 'طريقة الدفع', en: 'Payment Method', fr: 'Méthode de paiement', de: 'Zahlungsmethode', es: 'Método de pago' },
  date: { ar: 'التاريخ', en: 'Date', fr: 'Date', de: 'Datum', es: 'Fecha' },
  wallet: { ar: 'محفظة', en: 'Wallet', fr: 'Portefeuille', de: 'Wallet', es: 'Billetera' },
  creditCard: { ar: 'بطاقة ائتمان', en: 'Credit Card', fr: 'Carte de crédit', de: 'Kreditkarte', es: 'Tarjeta de crédito' },
  bankTransfer: { ar: 'تحويل بنكي', en: 'Bank Transfer', fr: 'Virement bancaire', de: 'Banküberweisung', es: 'Transferencia bancaria' },
  cash: { ar: 'نقدي', en: 'Cash', fr: 'Espèces', de: 'Bar', es: 'Efectivo' },
  manageStudents: { ar: 'إدارة الطلاب', en: 'Manage Students', fr: 'Gérer les étudiants', de: 'Schüler verwalten', es: 'Gestionar estudiantes' },
  studentsDescription: { ar: 'متابعة جميع الطلاب المسجلين وتقدمهم', en: 'Track all enrolled students and their progress', fr: 'Suivre tous les étudiants inscrits et leurs progrès', de: 'Verfolgen Sie alle eingeschriebenen Schüler und ihren Fortschritt', es: 'Seguir todos los estudiantes inscritos y su progreso' },
  noStudents: { ar: 'لا يوجد طلاب', en: 'No students', fr: 'Aucun étudiant', de: 'Keine Schüler', es: 'Sin estudiantes' },
  enrolledCourses: { ar: 'الدورات المسجلة', en: 'Enrolled Courses', fr: 'Cours inscrits', de: 'Eingeschriebene Kurse', es: 'Cursos inscritos' },
  noEnrolledCourses: { ar: 'لا يوجد دورات مسجلة', en: 'No enrolled courses', fr: 'Aucun cours inscrit', de: 'Keine eingeschriebenen Kurse', es: 'Sin cursos inscritos' },
  settingsSaved: { ar: 'تم حفظ الإعدادات بنجاح', en: 'Settings saved successfully', fr: 'Paramètres enregistrés avec succès', de: 'Einstellungen erfolgreich gespeichert', es: 'Configuración guardada con éxito' },
  passwordMismatch: { ar: 'كلمة المرور الجديدة وتأكيدها غير متطابقين', en: 'New password and confirmation do not match', fr: 'Le nouveau mot de passe et sa confirmation ne correspondent pas', de: 'Neues Passwort und Bestätigung stimmen nicht überein', es: 'La nueva contraseña y su confirmación no coinciden' },
  passwordChanged: { ar: 'تم تغيير كلمة المرور بنجاح', en: 'Password changed successfully', fr: 'Mot de passe modifié avec succès', de: 'Passwort erfolgreich geändert', es: 'Contraseña cambiada con éxito' },
  darkMode: { ar: 'الوضع الليلي', en: 'Dark Mode', fr: 'Mode sombre', de: 'Dunkler Modus', es: 'Modo oscuro' },
  darkModeDescription: { ar: 'تفعيل أو تعطيل المظهر الداكن', en: 'Enable or disable dark theme', fr: 'Activer ou désactiver le thème sombre', de: 'Dunkles Design aktivieren oder deaktivieren', es: 'Activar o desactivar el tema oscuro' },
  platformNotifications: { ar: 'تنبيهات المنصة', en: 'Platform Notifications', fr: 'Notifications de la plateforme', de: 'Plattform-Benachrichtigungen', es: 'Notificaciones de la plataforma' },
  platformNotificationsDescription: { ar: 'تلقي إشعارات عن التحديثات والأنشطة', en: 'Receive notifications about updates and activities', fr: 'Recevoir des notifications sur les mises à jour et les activités', de: 'Benachrichtigungen über Updates und Aktivitäten erhalten', es: 'Recibir notificaciones sobre actualizaciones y actividades' },
  emailNotifications: { ar: 'إشعارات البريد الإلكتروني', en: 'Email Notifications', fr: 'Notifications par e-mail', de: 'E-Mail-Benachrichtigungen', es: 'Notificaciones por correo electrónico' },
  emailNotificationsDescription: { ar: 'تلقي رسائل بريد إلكتروني حول الدورات', en: 'Receive email messages about courses', fr: 'Recevoir des e-mails concernant les cours', de: 'E-Mails zu Kursen erhalten', es: 'Recibir mensajes de correo sobre los cursos' },
  saveSettings: { ar: 'حفظ الإعدادات', en: 'Save Settings', fr: 'Enregistrer les paramètres', de: 'Einstellungen speichern', es: 'Guardar configuración' },
  security: { ar: 'الأمان', en: 'Security', fr: 'Sécurité', de: 'Sicherheit', es: 'Seguridad' },
  currentPassword: { ar: 'كلمة المرور الحالية', en: 'Current Password', fr: 'Mot de passe actuel', de: 'Aktuelles Passwort', es: 'Contraseña actual' },
  newPassword: { ar: 'كلمة المرور الجديدة', en: 'New Password', fr: 'Nouveau mot de passe', de: 'Neues Passwort', es: 'Nueva contraseña' },
  confirmPassword: { ar: 'تأكيد كلمة المرور', en: 'Confirm Password', fr: 'Confirmer le mot de passe', de: 'Passwort bestätigen', es: 'Confirmar contraseña' },
  changePassword: { ar: 'تغيير كلمة المرور', en: 'Change Password', fr: 'Changer le mot de passe', de: 'Passwort ändern', es: 'Cambiar contraseña' },
  settingsSaved: { ar: 'تم حفظ الإعدادات بنجاح', en: 'Settings saved successfully', fr: 'Paramètres enregistrés avec succès', de: 'Einstellungen erfolgreich gespeichert', es: 'Configuración guardada con éxito' },
  settingsSaveFailed: { ar: 'فشل حفظ الإعدادات', en: 'Failed to save settings', fr: 'Échec de l\'enregistrement des paramètres', de: 'Fehler beim Speichern der Einstellungen', es: 'Error al guardar la configuración' },
  unexpectedError: { ar: 'حدث خطأ', en: 'An error occurred', fr: 'Une erreur s\'est produite', de: 'Ein Fehler ist aufgetreten', es: 'Ocurrió un error' },
  loadingSettings: { ar: 'جاري تحميل الإعدادات...', en: 'Loading settings...', fr: 'Chargement des paramètres...', de: 'Einstellungen werden geladen...', es: 'Cargando configuración...' },
  platformSettings: { ar: 'إعدادات المنصة', en: 'Platform Settings', fr: 'Paramètres de la plateforme', de: 'Plattformeinstellungen', es: 'Configuración de la plataforma' },
  platformSettingsDescription: { ar: 'التحكم في إعدادات الموقع والتواصل', en: 'Control site and communication settings', fr: 'Contrôler les paramètres du site et de la communication', de: 'Website- und Kommunikationseinstellungen verwalten', es: 'Controlar la configuración del sitio y la comunicación' },
  generalInfo: { ar: 'المعلومات العامة', en: 'General Information', fr: 'Informations générales', de: 'Allgemeine Informationen', es: 'Información general' },
  siteName: { ar: 'اسم الموقع', en: 'Site Name', fr: 'Nom du site', de: 'Seitenname', es: 'Nombre del sitio' },
  siteDescription: { ar: 'وصف الموقع', en: 'Site Description', fr: 'Description du site', de: 'Seitenbeschreibung', es: 'Descripción del sitio' },
  logoUrl: { ar: 'رابط الشعار', en: 'Logo URL', fr: 'URL du logo', de: 'Logo-URL', es: 'URL del logo' },
  supportEmail: { ar: 'بريد الدعم', en: 'Support Email', fr: 'E-mail de support', de: 'Support-E-Mail', es: 'Correo de soporte' },
  emailSettings: { ar: 'إعدادات البريد الإلكتروني', en: 'Email Settings', fr: 'Paramètres de messagerie', de: 'E-Mail-Einstellungen', es: 'Configuración de correo' },
  smtpHost: { ar: 'خادم SMTP', en: 'SMTP Host', fr: 'Serveur SMTP', de: 'SMTP-Host', es: 'Servidor SMTP' },
  smtpPort: { ar: 'منفذ SMTP', en: 'SMTP Port', fr: 'Port SMTP', de: 'SMTP-Port', es: 'Puerto SMTP' },
  smtpUsername: { ar: 'اسم مستخدم SMTP', en: 'SMTP Username', fr: 'Nom d\'utilisateur SMTP', de: 'SMTP-Benutzername', es: 'Usuario SMTP' },
  smtpPassword: { ar: 'كلمة مرور SMTP', en: 'SMTP Password', fr: 'Mot de passe SMTP', de: 'SMTP-Passwort', es: 'Contraseña SMTP' },
  systemSettings: { ar: 'إعدادات النظام', en: 'System Settings', fr: 'Paramètres système', de: 'Systemeinstellungen', es: 'Configuración del sistema' },
  maintenanceMode: { ar: 'وضع الصيانة', en: 'Maintenance Mode', fr: 'Mode maintenance', de: 'Wartungsmodus', es: 'Modo mantenimiento' },
  maintenanceModeDescription: { ar: 'تعطيل الوصول للموقع للزوار أثناء الصيانة', en: 'Disable site access for visitors during maintenance', fr: 'Désactiver l\'accès au site pour les visiteurs pendant la maintenance', de: 'Seitenzugriff für Besucher während der Wartung deaktivieren', es: 'Desactivar el acceso al sitio para visitantes durante el mantenimiento' },
  saving: { ar: 'جاري الحفظ...', en: 'Saving...', fr: 'Enregistrement...', de: 'Speichern...', es: 'Guardando...' },
  reload: { ar: 'إعادة تحميل', en: 'Reload', fr: 'Recharger', de: 'Neu laden', es: 'Recargar' },
  unexpectedError: { ar: 'حدث خطأ غير متوقع', en: 'An unexpected error occurred', fr: 'Une erreur inattendue s\'est produite', de: 'Ein unerwarteter Fehler ist aufgetreten', es: 'Ocurrió un error inesperado' },
  errorDescription: { ar: 'تعذّر إكمال الطلب الآن. جرّب مرة أخرى، وإن استمرت المشكلة تواصل مع الدعم.', en: 'Could not complete the request. Try again, and if the issue persists, contact support.', fr: 'Impossible de traiter la demande. Réessayez et, si le problème persiste, contactez le support.', de: 'Anfrage konnte nicht abgeschlossen werden. Versuchen Sie es erneut und kontaktieren Sie bei anhaltenden Problemen den Support.', es: 'No se pudo completar la solicitud. Intenta de nuevo y, si el problema continúa, contacta con soporte.' },
  retry: { ar: 'إعادة المحاولة', en: 'Retry', fr: 'Réessayer', de: 'Erneut versuchen', es: 'Reintentar' },
  loadingPage: { ar: 'جاري تحميل الصفحة', en: 'Loading page', fr: 'Chargement de la page', de: 'Seite wird geladen', es: 'Cargando página' },
  enrolledStudentsInMyCourses: { ar: 'الطلاب المسجلون في دوراتي', en: 'Students enrolled in my courses', fr: 'Étudiants inscrits dans mes cours', de: 'Eingeschriebene Schüler in meinen Kursen', es: 'Estudiantes inscritos en mis cursos' },
  searchStudentPlaceholder: { ar: 'بحث عن طالب...', en: 'Search for a student...', fr: 'Rechercher un étudiant...', de: 'Nach einem Schüler suchen...', es: 'Buscar un estudiante...' },
  allCourses: { ar: 'كل الدورات', en: 'All Courses', fr: 'Tous les cours', de: 'Alle Kurse', es: 'Todos los cursos' },
  loadingData: { ar: 'جاري تحميل البيانات...', en: 'Loading data...', fr: 'Chargement des données...', de: 'Daten werden geladen...', es: 'Cargando datos...' },
  noEnrolledStudentsYet: { ar: 'لا يوجد طلاب مسجلون بعد', en: 'No enrolled students yet', fr: 'Aucun étudiant inscrit pour le moment', de: 'Noch keine eingeschriebenen Schüler', es: 'Aún no hay estudiantes inscritos' },
  enrolledCourse: { ar: 'الكورس المسجل به', en: 'Enrolled Course', fr: 'Cours inscrit', de: 'Eingeschriebener Kurs', es: 'Curso inscrito' },
  enrollmentDate: { ar: 'تاريخ التسجيل', en: 'Enrollment Date', fr: 'Date d\'inscription', de: 'Einschreibungsdatum', es: 'Fecha de inscripción' },
  quickHelp: { ar: 'مساعدة سريعة', en: 'Quick Help', fr: 'Aide rapide', de: 'Schnellhilfe', es: 'Ayuda rápida' },
  chatSupportDescription: { ar: 'تحدث مباشرة مع فريق الدعم عبر المحادثات الفورية.', en: 'Chat directly with the support team via live chat.', fr: 'Discutez directement avec l\'équipe de support via le chat en direct.', de: 'Chatten Sie direkt mit dem Support-Team per Live-Chat.', es: 'Chatea directamente con el equipo de soporte.' },
  openChats: { ar: 'فتح المحادثات', en: 'Open Chats', fr: 'Ouvrir les discussions', de: 'Chats öffnen', es: 'Abrir chats' },
  emailSupport: { ar: 'دعم عبر البريد', en: 'Email Support', fr: 'Support par e-mail', de: 'E-Mail-Support', es: 'Soporte por correo' },
  emailSupportDescription: { ar: 'أرسل استفسارك وسيتم الرد خلال 24 ساعة.', en: 'Send your inquiry and get a reply within 24 hours.', fr: 'Envoyez votre demande et recevez une réponse sous 24h.', de: 'Senden Sie Ihre Anfrage und erhalten Sie innerhalb von 24 Stunden eine Antwort.', es: 'Envía tu consulta y recibe respuesta en 24 horas.' },
  supportHours: { ar: 'ساعات الدعم', en: 'Support Hours', fr: 'Heures de support', de: 'Support-Stunden', es: 'Horario de soporte' },
  supportHoursDescription: { ar: 'فريقنا متاح يومياً من 9 صباحاً حتى 10 مساءً.', en: 'Our team is available daily from 9 AM to 10 PM.', fr: 'Notre équipe est disponible tous les jours de 9h à 22h.', de: 'Unser Team ist täglich von 9 bis 22 Uhr verfügbar.', es: 'Nuestro equipo está disponible diariamente de 9 AM a 10 PM.' },
  dailySupportHours: { ar: '9 صباحاً - 10 مساءً', en: '9 AM - 10 PM', fr: '9h - 22h', de: '9 - 22 Uhr', es: '9 AM - 10 PM' },
  howCanWeHelp: { ar: 'كيف يمكننا مساعدتك؟', en: 'How can we help you?', fr: 'Comment pouvons-nous vous aider ?', de: 'Wie können wir Ihnen helfen?', es: '¿Cómo podemos ayudarte?' },
  supportTeamReady: { ar: 'فريق الدعم لدينا جاهز لمساعدتك في أي استفسار.', en: 'Our support team is ready to help you with any inquiry.', fr: 'Notre équipe de support est prête à vous aider pour toute demande.', de: 'Unser Support-Team steht bereit, Ihnen bei Fragen zu helfen.', es: 'Nuestro equipo de soporte está listo para ayudarte.' },
  secureSupportTitle: { ar: 'دعم آمن ومشفر', en: 'Secure & Encrypted Support', fr: 'Support sécurisé et chiffré', de: 'Sicherer & verschlüsselter Support', es: 'Soporte seguro y encriptado' },
  secureSupportDescription: { ar: 'جميع المحادثات مشفرة لحماية خصوصيتك.', en: 'All chats are encrypted to protect your privacy.', fr: 'Toutes les discussions sont chiffrées pour protéger votre vie privée.', de: 'Alle Chats sind verschlüsselt, um Ihre Privatsphäre zu schützen.', es: 'Todos los chats están encriptados para proteger tu privacidad.' },
  allNotifications: { ar: 'كل الإشعارات', en: 'All Notifications', fr: 'Toutes les notifications', de: 'Alle Benachrichtigungen', es: 'Todas las notificaciones' },
  certificatesRecord: { ar: 'سجل الشهادات', en: 'Certificates Record', fr: 'Registre des certificats', de: 'Zertifikatsregister', es: 'Registro de certificados' },
  certificatesDescription: { ar: 'جميع الشهادات الصادرة للطلاب والمحاضرين.', en: 'All certificates issued to students and instructors.', fr: 'Tous les certificats délivrés aux étudiants et instructeurs.', de: 'Alle an Schüler und Dozenten ausgestellten Zertifikate.', es: 'Todos los certificados emitidos a estudiantes e instructores.' },
  searchCertificatesPlaceholder: { ar: 'ابحث عن شهادة...', en: 'Search certificates...', fr: 'Rechercher des certificats...', de: 'Zertifikate suchen...', es: 'Buscar certificados...' },
  noCertificates: { ar: 'لا توجد شهادات صادرة بعد', en: 'No certificates issued yet', fr: 'Aucun certificat délivré pour le moment', de: 'Noch keine Zertifikate ausgestellt', es: 'Aún no hay certificados emitidos' },
  certificateCode: { ar: 'كود الشهادة', en: 'Certificate Code', fr: 'Code du certificat', de: 'Zertifikatscode', es: 'Código del certificado' },
  viewQR: { ar: 'عرض QR', en: 'View QR', fr: 'Voir QR', de: 'QR ansehen', es: 'Ver QR' },
  scanQRToVerify: { ar: 'امسح الكود للتحقق من صحة الشهادة', en: 'Scan the code to verify the certificate', fr: 'Scannez le code pour vérifier le certificat', de: 'Scannen Sie den Code, um das Zertifikat zu verifizieren', es: 'Escanea el código para verificar el certificado' },
  revokeCertificate: { ar: 'إلغاء الشهادة', en: 'Revoke Certificate', fr: 'Révoquer le certificat', de: 'Zertifikat widerrufen', es: 'Revocar certificado' },
  confirmRevokeCertificate: { ar: 'هل أنت متأكد من إلغاء هذه الشهادة؟ لا يمكن التراجع.', en: 'Are you sure you want to revoke this certificate? This cannot be undone.', fr: 'Êtes-vous sûr de vouloir révoquer ce certificat ? Cette action est irréversible.', de: 'Sind Sie sicher, dass Sie dieses Zertifikat widerrufen möchten? Dies kann nicht rückgängig gemacht werden.', es: '¿Estás seguro de revocar este certificado? No se puede deshacer.' },
  explanationDocument: { ar: 'الملف التوضيحي', en: 'Explanation Document', fr: 'Document explicatif', de: 'Erläuterungsdokument', es: 'Documento explicativo' },
  pdfDefaultText: { ar: 'افتح الملف لمراجعة المحتوى قبل بدء الاختبار.', en: 'Open the file to review content before starting the quiz.', fr: 'Ouvrez le fichier pour examiner le contenu avant de commencer le quiz.', de: 'Öffnen Sie die Datei, um den Inhalt vor dem Quiz zu überprüfen.', es: 'Abre el archivo para revisar el contenido antes de iniciar el cuestionario.' },
  readDocumentBeforeQuiz: { ar: 'يرجى قراءة الملف قبل بدء الاختبار.', en: 'Please read the document before starting the quiz.', fr: 'Veuillez lire le document avant de commencer le quiz.', de: 'Bitte lesen Sie das Dokument, bevor Sie das Quiz starten.', es: 'Por favor lee el documento antes de iniciar el cuestionario.' },
  downloadPdf: { ar: 'تحميل PDF', en: 'Download PDF', fr: 'Télécharger PDF', de: 'PDF herunterladen', es: 'Descargar PDF' },
  readingCompleted: { ar: 'تمت القراءة', en: 'Reading Completed', fr: 'Lecture terminée', de: 'Lektüre abgeschlossen', es: 'Lectura completada' },
  csvExportSimulation: { ar: 'تصدير CSV', en: 'Export CSV', fr: 'Exporter CSV', de: 'CSV exportieren', es: 'Exportar CSV' },
  pdfExportSimulation: { ar: 'تصدير PDF', en: 'Export PDF', fr: 'Exporter PDF', de: 'PDF exportieren', es: 'Exportar PDF' },
  loadingReports: { ar: 'جاري تحميل التقارير...', en: 'Loading reports...', fr: 'Chargement des rapports...', de: 'Berichte werden geladen...', es: 'Cargando informes...' },
  passingScore: { ar: 'نسبة النجاح', en: 'Passing Score', fr: 'Score de réussite', de: 'Bestehspunktzahl', es: 'Puntuación de aprobación' },
  time: { ar: 'الوقت', en: 'Time', fr: 'Temps', de: 'Zeit', es: 'Tiempo' },
  description: { ar: 'الوصف', en: 'Description', fr: 'Description', de: 'Beschreibung', es: 'Descripción' },
  type: { ar: 'النوع', en: 'Type', fr: 'Type', de: 'Typ', es: 'Tipo' },
  order: { ar: 'الترتيب', en: 'Order', fr: 'Ordre', de: 'Reihenfolge', es: 'Orden' },
  createFailed: { ar: 'فشل الإنشاء', en: 'Creation failed', fr: 'Échec de la création', de: 'Erstellung fehlgeschlagen', es: 'Error al crear' },
  usersRolesControl: { ar: 'التحكم في المستخدمين والصلاحيات', en: 'Users & Roles Control', fr: 'Gestion des utilisateurs et rôles', de: 'Benutzer- und Rollenverwaltung', es: 'Control de usuarios y roles' },
  accountRole: { ar: 'الدور الحسابي', en: 'Account Role', fr: 'Rôle du compte', de: 'Kontorolle', es: 'Rol de la cuenta' },
  deleteUserConfirm: { ar: 'هل أنت متأكد من حذف هذا المستخدم نهائياً؟ لا يمكن التراجع عن هذا الإجراء.', en: 'Are you sure you want to permanently delete this user? This action cannot be undone.', fr: 'Êtes-vous sûr de vouloir supprimer définitivement cet utilisateur ? Cette action est irréversible.', de: 'Sind Sie sicher, dass Sie diesen Benutzer dauerhaft löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.', es: '¿Estás seguro de que quieres eliminar permanentemente este usuario? Esta acción no se puede deshacer.' },
  levels: { ar: 'المستويات', en: 'Levels', fr: 'Niveaux', de: 'Levels', es: 'Niveles' },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: 'rtl' | 'ltr'
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ar',
  setLanguage: () => {},
  t: (key) => key,
  dir: 'rtl',
  isRTL: true,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar')

  const t = (key: string) => {
    return translations[key]?.[language] || key
  }

  const dir = language === 'ar' ? 'rtl' : 'ltr'
  const isRTL = dir === 'rtl'

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = dir
  }, [language, dir])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
